#include "./uniforms_textures"
#include "./uniforms_intensity_map"
#include "./uniforms_color_map"
#include "./uniforms_minima_distance_map"
#include "./uniforms_maxima_distance_map"
#include "./uniforms_rendering"
#include "./uniforms_shading"
#include "./uniforms_debugging"
