#include "./uniforms_textures"
#include "./uniforms_volume"
#include "./uniforms_distmap"
#include "./uniforms_rendering"
#include "./uniforms_colormap"
#include "./uniforms_shading"
#include "./uniforms_debugging"
