#include "./debug_frag_depth"               // case  1
#include "./debug_ray_intersected"          // case  2
#include "./debug_ray_step_direction"       // case  3
#include "./debug_ray_step_distance"        // case  4
#include "./debug_ray_rand_distance"        // case  5
#include "./debug_ray_start_distance"       // case  6
#include "./debug_ray_end_distance"         // case  7
#include "./debug_ray_span_distance"        // case  8
#include "./debug_ray_start_position"       // case  9
#include "./debug_ray_end_position"         // case 10
#include "./debug_ray_box_start_distance"   // case 11
#include "./debug_ray_box_end_distance"     // case 12
#include "./debug_ray_box_span_distance"    // case 13
#include "./debug_ray_box_start_position"   // case 14
#include "./debug_ray_box_end_position"     // case 15
#include "./debug_ray_max_step_count"       // case 16
#include "./debug_ray_max_skip_count"       // case 17
#include "./debug_trace_block_coords"       // case 18
#include "./debug_trace_block_lod"          // case 19
#include "./debug_trace_block_occupancy"    // case 20
#include "./debug_trace_block_occupied"     // case 21
#include "./debug_trace_derivative_1st"     // case 22
#include "./debug_trace_derivative_2nd"     // case 23
#include "./debug_trace_derivative_3rd"     // case 24
#include "./debug_trace_distance"           // case 25
#include "./debug_trace_distance_error"     // case 26
#include "./debug_trace_distance_diff"      // case 27
#include "./debug_trace_gradient_magnitude" // case 28
#include "./debug_trace_gradient"           // case 29
#include "./debug_trace_luminance"          // case 30
#include "./debug_trace_mapped_color"       // case 31
#include "./debug_trace_mean_step_distance" // case 32
#include "./debug_trace_normal"             // case 33
#include "./debug_trace_outside"            // case 34
#include "./debug_trace_position"           // case 35
#include "./debug_trace_sample_abs_error"   // case 36
#include "./debug_trace_sample_error"       // case 37
#include "./debug_trace_sample_value"       // case 38
#include "./debug_trace_shaded_color"       // case 39
#include "./debug_trace_skip_count"         // case 40
#include "./debug_trace_skip_distance"      // case 41
#include "./debug_trace_skipped_distance"   // case 42
#include "./debug_trace_spanned_distance"   // case 43
#include "./debug_trace_step_count"         // case 44
#include "./debug_trace_step_distance"      // case 45
#include "./debug_trace_step_scaling"       // case 46
#include "./debug_trace_step_stretching"    // case 47
#include "./debug_trace_stepped_distance"   // case 48
#include "./debug_trace_voxel_coords"       // case 49
#include "./debug_trace_total_count"        // case 50

