#include "./uniforms_sampler"
#include "./uniforms_volume"
#include "./uniforms_occupancy"
#include "./uniforms_raycast"
#include "./uniforms_gradient"
#include "./uniforms_colormap"
#include "./uniforms_lighting"
#include "./uniforms_debug"