#include "./debug_frag_depth"               
#include "./debug_ray_camera_position"       
#include "./debug_ray_camera_direction"       
#include "./debug_ray_step_direction"       
#include "./debug_ray_step_distance"             
#include "./debug_ray_rand_distance"        
#include "./debug_ray_start_distance"       
#include "./debug_ray_end_distance"         
#include "./debug_ray_span_distance"        
#include "./debug_ray_start_position"       
#include "./debug_ray_end_position"         
#include "./debug_ray_max_step_count"       
#include "./debug_ray_min_start_distance"       
#include "./debug_ray_max_end_distance"       
#include "./debug_ray_max_span_distance"  

#include "./debug_trace_terminated"         
#include "./debug_trace_suspended"          
#include "./debug_trace_distance"   
#include "./debug_trace_position"  
#include "./debug_trace_voxel_coords"       
#include "./debug_trace_step_count"         
#include "./debug_trace_step_distance"      
#include "./debug_trace_step_scaling"
#include "./debug_trace_mean_step_scaling"  
#include "./debug_trace_mean_step_distance"  

#include "./debug_max_trace_distance"   
#include "./debug_max_trace_position"  
#include "./debug_max_trace_voxel_coords"       
#include "./debug_max_trace_step_count"         
#include "./debug_max_trace_step_distance"
#include "./debug_max_trace_step_scaling"
#include "./debug_max_trace_sample_value"  
#include "./debug_max_trace_mapped_color" 
#include "./debug_max_trace_gradient" 
#include "./debug_max_trace_gradient_magnitude" 
#include "./debug_max_trace_gradient_direction" 
#include "./debug_max_trace_derivative"         


